import { HistoricalFigure } from '@/types';

export const HISTORICAL_FIGURES: HistoricalFigure[] = [
  {
    id: 'amir-temur',
    name: 'Amir Temur',
    fullName: 'Sohibqiron Amir Temur Ko‘ragoniy',
    title: 'Buyuk Sarkarda, Davlat Arbobi va Sohibqiron',
    period: '1336 – 1405-yillar',
    motto: '“Kuch — adolatdadir!”',
    shortBio: 'Markaziy Osiyoda markazlashgan qudratli davlat barpo etgan, ilm-fan, madaniyat va me’morchilikni mislsiz darajada rivojlantirgan jahongir.',
    portrait: '/images/amir_temur.jpg',
    voice: 'male',
    category: 'sarkardalar',
    color: '#D97706',
    accentBg: '#FFFBEB',
    accentBorder: '#FDE68A',
    greetingSpeech: `Assalomu alaykum, aziz avlodim! Men Sohibqiron Amir Temurman. Bizning qudratimizga shubha qilsangiz, biz qurgan obidalarga va adolatli tuzuklarimizga boqing! Qaysi mavzuda suhbatlashamiz?`,
    topics: [
      {
        id: 'temur-bio',
        title: 'Men haqimda bilmoqchimisiz?',
        icon: '👑',
        question: 'Amir Temur haqida qisqacha ma’lumot',
        speechText: `Men Amir Temur Tarag‘ay Bahodir o‘g‘li, Kesh zaminida tavallud topganman. Butun hayotimni xalqimizni birlashtirish, o‘zaro nizo va parokandalikka barham berish hamda Samarqandni jahonning eng go‘zal va obod poytaxtiga aylantirishga bag‘ishladim.`,
      },
      {
        id: 'temur-justice',
        title: 'Kuch — adolatdadir ma’nosi',
        icon: '⚖️',
        question: '“Kuch — adolatdadir” shiori nimani anglatadi?',
        speechText: `Adolat — davlat poydevori va har bir rahbarning eng oliy burchidir. Adolatsiz qudrat — zulmdir, qudratsiz adolat esa ojizlikdir. Shu sababli, har bir ishimda haqiqat, tenglik va qonun ustuvorligini bosh mezon qilib belgilaganman.`,
      },
      {
        id: 'temur-tuzuklar',
        title: 'Temur tuzuklari va boshqaruv',
        icon: '📜',
        question: 'Temur tuzuklarining asosiy saboqlari qanday?',
        speechText: `Tuzuklarimda yozganman: Yuz ming otliq askar qila olmagan ishni bir to‘g‘ri tadbir va aql bilan amalga oshirish mumkin. Davlatni boshqarishda kengash, tadbirkorlik, hushyorlik va ilm ahlini qadrlash asosiy yo‘ldir.`,
      },
      {
        id: 'temur-youth',
        title: 'Kelajak yoshlariga o‘gitlarim',
        icon: '🌟',
        question: 'Zamonaviy yoshlarga qanday vasiyatingiz bor?',
        speechText: `Ey aziz yoshlar! Doimo azmu shijoatli, intizomli va o‘z maqsadingizga sadoqatli bo‘ling. Ota-onani e’zozlang, ustozlarni hurmat qiling, har bir daqiqani ilm o‘rganish va vatan ravnaqiga sarflang. Sizlar buyuk xalqning munosib davomchilarisiz!`,
      },
    ],
  },
  {
    id: 'alisher-navoiy',
    name: 'Alisher Navoiy',
    fullName: 'Nizomiddin Mir Alisher Navoiy',
    title: 'Hazrat, Buyuk Shoir, Mutafakkir va Davlat Arbobi',
    period: '1441 – 1501-yillar',
    motto: '“Olam ahli, bilingizkim, ish emas dushmanlig‘...”',
    shortBio: 'O‘zbek adabiy tilining asoschisi, besh dostonni jamlagan buyuk “Xamsa” muallifi va ma’naviyat quyoshi.',
    portrait: '/images/alisher_navoiy.jpg',
    voice: 'male',
    category: 'allomalar',
    color: '#059669',
    accentBg: '#ECFDF5',
    accentBorder: '#A7F3D0',
    greetingSpeech: `Assalomu alaykum, ilm va ma’rifat tolibi! Men faqir Alisher Navoiyman. Til va adabiyot, saxovat va insoniylik sirlarini birga mutolaa qilishdan behad mamnunman.`,
    topics: [
      {
        id: 'navoiy-language',
        title: 'Ona tilimizning buyukligi',
        icon: '✍️',
        question: 'O‘zbek tilining boyligi haqida',
        speechText: `Turkiy til shunday bir gavhardirki, uning qadrini bilmaganlar bu boylikdan bebahra qolur. Men "Muhokamat ul-lug‘atayn" asarimda turkiy tilning naqadar boy, nozik va cheksiz imkoniyatlarga ega ekanligini isbotlab berdim. Ona tilingizni asrang va uning ravnaqi uchun xizmat qiling!`,
      },
      {
        id: 'navoiy-khamsa',
        title: '“Xamsa” dostonlari haqida',
        icon: '📚',
        question: 'Xamsa dostonlari qanday yaratilgan?',
        speechText: `Turkiy tilda ilk bor besh doston — "Xamsa"ni yaratish menga nasib etdi: Hayrat ul-abror, Farhod va Shirin, Layli va Majnun, Sab’ai sayyor va Saddi Iskandariy. Bu dostonlarda adolat, sevgi, qahramonlik va ilm yo‘lidagi sabr-toqat tarannum etilgan.`,
      },
      {
        id: 'navoiy-gazal',
        title: 'Mashhur g‘azalidan parcha',
        icon: '🎵',
        question: 'Alisher Navoiy g‘azalidan tinglash',
        speechText: `Qaro ko‘zum, kel-u mardumlig‘ emdi fan qilg‘il, Ko‘zum qorasida mardum kibi vatan qilg‘il. Yuzing guliga ko‘ngul ravzasin yorug‘ aylab, Jamoling orazidin husn anjuman qilg‘il. Sevgi va go‘zallik inson qalbining eng oliy ziynatidir.`,
      },
      {
        id: 'navoiy-advice',
        title: 'Yaxshilik va insoniylik hikmati',
        icon: '💎',
        question: 'Inson qanday yashashi kerak?',
        speechText: `Odamiy ersang, demagil odami, Onikim yo‘q xalq g‘amidin g‘ami. Insonning qadri — uning o‘zgalarga ko‘rsatgan himmati, saxovati va xalqiga qilgan beminnat xizmati bilan o‘lchanadi. Doimo ezgulik va yaxshilik ulashing!`,
      },
    ],
  },
  {
    id: 'mirzo-ulugbek',
    name: 'Mirzo Ulug‘bek',
    fullName: 'Muhammad Tarag‘ay Mirzo Ulug‘bek',
    title: 'Buyuk Astronom, Matematik Olim va Hukmdor',
    period: '1394 – 1449-yillar',
    motto: '“Ilm o‘rganmoq har bir musulmon erkak va ayolga farzdir.”',
    shortBio: 'Samarqandda ulkan rasadxona barpo etgan, 1018 ta yulduzning aniq koordinatalarini hisoblagan jahonshumul olim.',
    portrait: '/images/mirzo_ulugbek.jpg',
    voice: 'male',
    category: 'allomalar',
    color: '#0284C7',
    accentBg: '#F0F9FF',
    accentBorder: '#BAE6FD',
    greetingSpeech: `Salom, aziz yosh do‘stim! Men Mirzo Ulug‘bekman. Samarqand osmonidagi yulduzlar harakati va koinotning aniq hisob-kitoblari sirlarini siz bilan baham ko‘rishdan shodman.`,
    topics: [
      {
        id: 'ulugbek-observatory',
        title: 'Samarqand rasadxonasi',
        icon: '🔭',
        question: 'Rasadxona va koinotni o‘rganish haqida',
        speechText: `Samarqandda Kuxak tepaligida uch qavatli ulkan rasadxona bino qildirdim. Sekstant asbobi yordamida osmon jismlarining harakatini bir daqiqa-yu soniyasigacha o‘rganib, dunyo miqyosidagi eng aniq o‘lchovlarga erishdik.`,
      },
      {
        id: 'ulugbek-zij',
        title: '“Ziji Jadidi Ko‘ragoniy” asari',
        icon: '⭐',
        question: 'Yulduzlar jadvali qanday yaratilgan?',
        speechText: `Biz 1018 ta qo‘zg‘almas yulduzning koordinatasini aniqlab, "Ziji Jadidi Ko‘ragoniy" astronomik jadvalini tuzdik. Bir yilning davomiyligini 365 kun, 6 soat, 10 daqiqa va 8 soniya deb hisoblab chiqdik — bu zamonaviy hisobdan bor-yo‘g‘i bir necha soniyaga farq qiladi.`,
      },
      {
        id: 'ulugbek-academy',
        title: 'Samarqand ilmiy maktabi',
        icon: '🏛️',
        question: 'Qozi Zoda Rumiy va Ali Qushchi bilan hamkorlik',
        speechText: `Madrasamiz peshtoqiga "Ilm izlamoq har bir mo‘min va mo‘mina uchun burchdir" degan hadisni naqsh qildirdim. Qozizoda Rumiy, G‘iyosiddin Jamshid Koshiy va Ali Qushchi kabi yuzlab olimlar bilan birga Samarqandni ilm poytaxtiga aylantirdik.`,
      },
      {
        id: 'ulugbek-science',
        title: 'Aniq fanlar va kelajak',
        icon: '📐',
        question: 'Matematika va aniq fanlarning ahamiyati',
        speechText: `Matematika — barcha fanlarning kalitidir. Mantiqiy fikrlash va aniq hisob-kitob har qanday murakkab jumboqni yechishga imkon beradi. Bugungi zamonaviy texnologiyalar, sun’iy intellekt va koinot sirlarini egallash uchun matematika va fizikani chuqur o‘rganing!`,
      },
    ],
  },
  {
    id: 'mahmudxoja-behbudiy',
    name: 'Mahmudxo‘ja Behbudiy',
    fullName: 'Mahmudxo‘ja Behbudiy',
    title: 'Turkiston Jadidchilik Harakati Yetakchisi, Ma’rifatparvar',
    period: '1875 – 1919-yillar',
    motto: '“Haq olinur, berilmas!”',
    shortBio: 'Yangi usul maktablari tashkilotchisi, “Oyina” jurnali asoschisi va millatning ma’naviy ozodligi yo‘lida jon kuydirgan alloma.',
    portrait: '/images/mahmudxoja_behbudiy.jpg',
    voice: 'male',
    category: 'jadidlar',
    color: '#7C3AED',
    accentBg: '#F5F3FF',
    accentBorder: '#DDD6FE',
    greetingSpeech: `Assalomu alaykum, millatimiz umidi bo‘lgan aziz yoshlar! Men Mahmudxo‘ja Behbudiy bo‘laman. Taraqqiyot, matbuot, teatr va zamonaviy ilm haqida fikrlashishga shayman.`,
    topics: [
      {
        id: 'behbudiy-languages',
        title: '“Ikki emas, to‘rt til lozim”',
        icon: '🌍',
        question: 'Nega 4 ta til o‘rganishimiz kerak?',
        speechText: `Men 1913-yilda yozgan edim: Bizga bugun ikki emas, to‘rt til lozim! Ona tilimiz, mintaqaviy tillar hamda jahon tillarini mukammal bilishimiz shart. Dunyo ilm-fani, tijorati va texnologiyasiga faqat ko‘p til bilish orqali erisha olamiz!`,
      },
      {
        id: 'behbudiy-oyina',
        title: '“Oyina” jurnali va matbuot',
        icon: '📰',
        question: '“Oyina” jurnali va milliy matbuotimiz',
        speechText: `1913-yilda Samarqandda "Oyina" ma’rifiy jurnalini ta’sis etdim. Jurnal orqali millatning ko‘zini ochish, xurofot va jaholatga qarshi kurashish, dunyodagi yangiliklarni xalqimizga yetkazishni maqsad qildik. Matbuot — xalqning ko‘zgusi va ovozidir.`,
      },
      {
        id: 'behbudiy-padarkush',
        title: '“Padarkush” dramasi va teatr',
        icon: '🎭',
        question: 'O‘zbek milliy teatrining boshlanishi',
        speechText: `Teatr — bu ibratxonadir. Ilmsizlik va noo‘rin isrofgarchilik oqibatlarini ko‘rsatish uchun "Padarkush" dramasini yozdim. Bu asar milliy teatr san’atimizga tamal toshini qo‘ydi va odamlarni farzandlariga zamonaviy ta’lim berishga undadi.`,
      },
      {
        id: 'behbudiy-schools',
        title: 'Yangi usul maktablari',
        icon: '🏫',
        question: 'Jadid maktablarining yangiligi nimada edi?',
        speechText: `Eski qotib qolgan tizim o‘rniga partalar, xaritalar, globus va qisqa muddatda savod chiqaruvchi tovush usulidagi yangi maktablar ochdik. Yoshlarimiz dunyoviy fanlar: matematika, jug‘rofiya, tarix va chet tillarini chuqur o‘rganishlari lozim.`,
      },
    ],
  },
  {
    id: 'abdulla-avloniy',
    name: 'Abdulla Avloniy',
    fullName: 'Abdulla Avloniy',
    title: 'Buyuk Pedagog, Jadid Adibi va Ma’rifatparvar',
    period: '1878 – 1934-yillar',
    motto: '“Tarbiya biz uchun yo hayot — yo mamot masalasidir.”',
    shortBio: '“Turkiy Guliston yoxud Axloq” asari muallifi, bolalar ta’limi va milliy pedagogika darg‘asi.',
    portrait: '/images/abdulla_avloniy.jpg',
    voice: 'male',
    category: 'jadidlar',
    color: '#E11D48',
    accentBg: '#FFF1F2',
    accentBorder: '#FECDD3',
    greetingSpeech: `Salom, aziz farzandim! Men muallim Abdulla Avloniyman. Odob-axloq, toza vijdonga ega bo‘lish va yuksak tarbiya sirlarini birga o‘rganamiz.`,
    topics: [
      {
        id: 'avloniy-tarbiya',
        title: 'Tarbiya — hayot yoki mamot',
        icon: '📖',
        question: 'Nega tarbiya eng muhim masala?',
        speechText: `Tarbiya biz uchun yo hayot — yo mamot, yo najot — yo halokat, yo saodat — yo falokat masalasidir! Har bir insonning kelajagi uning yoshlikda olgan to‘g‘ri tarbiyasi, vijdoni va o‘rgangan odobiga chambarchas bog‘liqdir.`,
      },
      {
        id: 'avloniy-axloq',
        title: '“Turkiy Guliston yoxud Axloq”',
        icon: '🌱',
        question: 'Go‘zal xulq va fazilatlar haqida',
        speechText: `Darsligimda yozgan edim: Insonning eng katta boyligi — bu uning go‘zal axloqi, rostgo‘yligi, mehnati va saxovatidir. G‘iybat, dangasalik va kibrdan yiroq bo‘ling. O‘zgalarga foyda keltirishni hayotingizning bosh maqsadi deb biling.`,
      },
      {
        id: 'avloniy-school',
        title: 'Maktab va muallimlik burchi',
        icon: '🎒',
        question: 'Maktab va o‘qituvchining qadri',
        speechText: `Maktab — insoniyatning najot maskanidir. Maktabda o‘qigan bola jaholat qorong‘uligidan ilm nuri sari qadam qo‘yadi. Ustoz va murabbiylarni qadrlang, chunki ular sizga hayot yo‘lini yorituvchi mayoqdirlar.`,
      },
      {
        id: 'avloniy-poetry',
        title: 'Yoshlarga she’riy murojaat',
        icon: '✨',
        question: 'Abdulla Avloniyning yoshlarga da’vati',
        speechText: `Bizni g‘aflat uyqusidan uyg‘otg‘usi ilm-u hunar, Millatni yuksak qilib, obod etgusi ilm-u hunar. Ey aziz bolalarim, doimo o‘qing, izlaning va yangi bilimlarni egallang. Kelajak sizning qo‘lingizda!`,
      },
    ],
  },
];
