import { LanguageCourse, CareerDirection, MigrationCountry, PsychologyCategory, AITool, TerminalStatus } from '@/types';

export const MOCK_LANGUAGES: LanguageCourse[] = [
  {
    id: 'en',
    name: 'Ingliz tili',
    flag: '🇬🇧',
    description: 'Xalqaro muloqot va ta’lim tili. IELTS, CEFR va so‘zlashuv kurslari.',
    levels: ['Boshlang‘ich (A1-A2)', 'O‘rta (B1-B2)', 'Yuqori (C1)'],
    features: ['IELT/CEFR tayyorlov', 'Interaktiv lug‘at', 'Video darslar', 'Listening mashqlar'],
    externalUrl: 'https://ibratfarzandlari.uz',
  },
  {
    id: 'ru',
    name: 'Rus tili',
    flag: '🇷🇺',
    description: 'MDH mamlakatlarida muloqot va biznes tili. Grammatika va so‘zlashuv.',
    levels: ['Boshlang‘ich', 'Erkin muloqot', 'Biznes rus tili'],
    features: ['So‘zlashuv klubi', 'Grammatika sodda shaklda', 'Audiokurslar'],
    externalUrl: 'https://ibratfarzandlari.uz',
  },
  {
    id: 'zh',
    name: 'Xitoy tili',
    flag: '🇨🇳',
    description: 'Zamonaviy savdo va texnologiya tili. HSK darajalari bo‘yicha ta’lim.',
    levels: ['HSK 1-2', 'HSK 3-4', 'HSK 5'],
    features: ['Iyerogliflar mashqi', 'Tonal talaffuz', 'Muloqot darslari'],
    externalUrl: 'https://ibratfarzandlari.uz',
  },
  {
    id: 'de',
    name: 'Nemis tili',
    flag: '🇩🇪',
    description: 'Germaniyada o‘qish va ishlash uchun zaruriy til (Goethe / Telc).',
    levels: ['A1-A2 (Boshlang‘ich)', 'B1-B2 (O‘qish va ish)'],
    features: ['Ausbildung uchun nemis tili', 'Goethe testlar', 'Lug‘at boyitish'],
    externalUrl: 'https://ibratfarzandlari.uz',
  },
  {
    id: 'es',
    name: 'Ispan tili',
    flag: '🇪🇸',
    description: 'Dunyodagi eng ko‘p so‘zlashiladigan tillardan biri. Ispaniya va Lotin Amerikasi tili.',
    levels: ['Boshlang‘ich (A1-A2)', 'O‘rta (B1-B2)', 'Yuqori (C1)'],
    features: ['So‘zlashuv mashqlari', 'Interaktiv grammatika', 'Audio darslar'],
    externalUrl: 'https://ibratfarzandlari.uz',
  },
  {
    id: 'tr',
    name: 'Turk tili',
    flag: '🇹🇷',
    description: 'Turkiya va qardosh xalqlar muloqot tili. Turkiyada o‘qish va biznes yuritish uchun.',
    levels: ['Boshlang‘ich (A1-A2)', 'Erkin muloqot (B1-C1)'],
    features: ['TÖMER tayyorlov', 'Turk seriallari va grammatika', 'So‘zlashuv mashqlari'],
    externalUrl: 'https://ibratfarzandlari.uz',
  },
];

export const MOCK_CAREERS: CareerDirection[] = [
  {
    id: 'web-dev',
    title: 'Web Dasturlash',
    icon: '💻',
    description: 'Frontend va Backend dasturlash: HTML, CSS, JavaScript, React, Python.',
    popular: true,
    skills: ['HTML/CSS', 'JavaScript', 'React', 'Node.js'],
    externalUrl: 'https://ustoz.ai',
  },
  {
    id: 'graphic-design',
    title: 'Grafik Dizayn',
    icon: '🎨',
    description: 'Photoshop, Illustrator, Figma orqali logo, brending va bannerlar yaratish.',
    popular: true,
    skills: ['Figma', 'Photoshop', 'Illustrator', 'UI/UX'],
    externalUrl: 'https://ustoz.ai',
  },
  {
    id: 'smm-marketing',
    title: 'SMM & Digital Marketing',
    icon: '📱',
    description: 'Ijtimoiy tarmoqlarda biznesni yuritish, target reklama va kontent reja.',
    popular: true,
    skills: ['Targeting', 'Copywriting', 'Content Strategy'],
    externalUrl: 'https://ustoz.ai',
  },
  {
    id: 'video-editing',
    title: 'Video Montaj',
    icon: '🎬',
    description: 'Premiere Pro va DaVinci Resolve orqali professional roliklar tayyorlash.',
    popular: false,
    skills: ['Premiere Pro', 'After Effects', 'Color Grading'],
    externalUrl: 'https://ustoz.ai',
  },
  {
    id: '3d-design',
    title: '3D Dizayn va Vizualizatsiya',
    icon: '🏗️',
    description: 'Blender va 3ds Max orqali model yaratish va interyer dizayni.',
    popular: false,
    skills: ['Blender', '3ds Max', 'Rendering'],
    externalUrl: 'https://ustoz.ai',
  },
  {
    id: 'ai-prompt',
    title: 'AI & Sun’iy Intellekt',
    icon: '🤖',
    description: 'ChatGPT, Midjourney va AI instrumentlardan professional foydalanish.',
    popular: true,
    skills: ['Prompt Engineering', 'AI Automation', 'LLM Tools'],
    externalUrl: 'https://ustoz.ai',
  },
];

export const MOCK_MIGRATION_COUNTRIES: MigrationCountry[] = [
  {
    id: 'germany',
    name: 'Germaniya',
    flag: '🇩🇪',
    code: 'DE',
    studyInfo: 'Universitetlar va Ausbildung (dual ta’lim). Nemis tili B1/B2 talab qilinadi.',
    workInfo: 'Chaqirilgan kasblar: Hamshira, Muhandis, IT mutaxassisi, Quruvchi, Oshpaz.',
    livingInfo: 'Yashash xarajatlari oylik 800-1100€. Sug‘urta va uy ijarsi majburiy.',
    requiredLanguage: 'Nemis tili (B1-B2) yoki Ingliz tili (IELTS 6.5+)',
    inDemandJobs: ['IT Dasturchi', 'Hamshiradorlik', 'Payvandchi', 'Logistika operatori'],
    salaryRange: '2,200€ – 4,500€ / oyiga',
    officialSources: [
      { title: 'Make it in Germany (Rasmiy Portal)', url: 'https://www.make-it-in-germany.com', date: '2026-08-01' },
      { title: 'O‘zbekiston Tashqi Mehnat Migratsiyasi Agentligi', url: 'https://migration.uz', date: '2026-07-25' },
    ],
  },
  {
    id: 'south-korea',
    name: 'Janubiy Koreya',
    flag: '🇰🇷',
    code: 'KR',
    studyInfo: 'D2 / D4 vizasi. Koreys tili TOPIK 3+ sertifikati va grant imkoniyatlari.',
    workInfo: 'EPS (E-9) tizimi orqali rasmiy zavod, qishloq xo‘jaligi va qurilish sohasi.',
    livingInfo: 'Madaniyatga tez moslashish va tartib-intizomga rioya qilish muhim.',
    requiredLanguage: 'Koreys tili (TOPIK 2/3) yoki EPS-TOPIK imtihoni',
    inDemandJobs: ['Zavod ishchisi', 'Avtomobil sanoati', 'Kemasozlik', 'Qishloq xo‘jaligi'],
    salaryRange: '1,800$ – 3,200$ / oyiga',
    officialSources: [
      { title: 'EPS Korea Rasmiy Tizimi', url: 'https://www.eps.go.kr', date: '2026-08-02' },
      { title: 'Migratsiya Agentligi Koreya Bo‘limi', url: 'https://migration.uz', date: '2026-07-30' },
    ],
  },
  {
    id: 'japan',
    name: 'Yaponiyada Ishlash va O‘qish',
    flag: '🇯🇵',
    code: 'JP',
    studyInfo: 'Til maktablari va texnik kollejlar. JLPT N4 / N3 darajasi zarur.',
    workInfo: 'Tokutei Ginou (Maxsus malakali ishchi) dasturi bo‘yicha 14 ta soha.',
    livingInfo: 'Yuksak intizom, tozalik va mehmondo‘stlik madaniyati.',
    requiredLanguage: 'Yapon tili (JLPT N4/N3)',
    inDemandJobs: ['Keksalar parvarishi', 'Mehmonxona xizmati', 'Qurilish', 'Oziq-ovqat sanoati'],
    salaryRange: '1,600$ – 3,000$ / oyiga',
    officialSources: [
      { title: 'Japan Official Immigration Agency', url: 'https://www.moj.go.jp/isa/', date: '2026-08-05' },
    ],
  },
  {
    id: 'uk',
    name: 'Buyuk Britaniya (UK)',
    flag: '🇬🇧',
    code: 'GB',
    studyInfo: 'Bakalavr va Magistratura. IELTS 6.5+ va moliyaviy kafolat.',
    workInfo: 'Skilled Worker Visa & Seasonal Worker Scheme (Mavsumiy qishloq xo‘jaligi).',
    livingInfo: 'Oylik xarajatlar va ijara narxi yuqori. Tibbiy sug‘urta (IHS) to‘lanadi.',
    requiredLanguage: 'Ingliz tili (IELTS / PTE Academic)',
    inDemandJobs: ['Qishloq xo‘jaligi terimchisi', 'Tibbiyot xodimi', 'IT loyiha menejeri'],
    salaryRange: '2,000£ – 5,000£ / oyiga',
    officialSources: [
      { title: 'UK Government Official Visa Portal', url: 'https://www.gov.uk/browse/visas-immigration', date: '2026-08-08' },
    ],
  },
];

export const MOCK_PSYCHOLOGY_CATEGORIES: PsychologyCategory[] = [
  { id: 'family', title: 'Oila va Munosabatlar', icon: '🏡', description: 'Oila a’zolari bilan samimiy va sog‘lom muloqotni tiklash.' },
  { id: 'study', title: 'O‘qish va Maktab', icon: '🎓', description: 'Imtihon oldidan hayajon, do‘stlar va ustozlar bilan munosabat.' },
  { id: 'stress', title: 'Stress va Charchoq', icon: '🌧️', description: 'Ruhiy toliqishni yengish va energiya darajasini tiklash.' },
  { id: 'motivation', title: 'Motivatsiya va Maqsad', icon: '🚀', description: 'O‘z kuchiga ishonch va kelajak rejalarini shakllantirish.' },
  { id: 'finance-pressure', title: 'Moliyaviy Bosim va Ish', icon: '💼', description: 'Ishdagi bosim, mas’uliyat va moliyaviy xavotirlar bilan ishlash.' },
];

export const MOCK_AI_TOOLS: AITool[] = [
  { id: 'chatgpt', name: 'ChatGPT / Open AI', category: 'Chat & Matn', description: 'Savol-javob, matn yozish va umumiy maslahatlar.', url: 'https://chat.openai.com', icon: '🤖', status: 'active' },
  { id: 'gemini', name: 'Google Gemini', category: 'Chat & Qidiruv', description: 'Google bilimlar bazasiga ulangan kuchli AI yordamchi.', url: 'https://gemini.google.com', icon: '✨', status: 'active' },
  { id: 'midjourney', name: 'Midjourney / Image AI', category: 'Rasm & Dizayn', description: 'Matn ko‘rinishidagi tavsifdan yuqori sifatli rasm yaratish.', url: 'https://midjourney.com', icon: '🎨', status: 'active' },
  { id: 'canva-ai', name: 'Canva Magic Studio', category: 'Prezentatsiya & Poster', description: 'Taqdimotlar, ijtimoiy tarmoq vizuallari yaratish.', url: 'https://canva.com', icon: '📐', status: 'active' },
  { id: 'suno', name: 'Suno AI Music', category: 'Musika', description: 'Matn asosida qo‘shiq va musiqa yaratish.', url: 'https://suno.ai', icon: '🎵', status: 'active' },
  { id: 'runway', name: 'Runway Gen-2 Video', category: 'Video', description: 'Matn yoki rasmdan professional video roliklar hosil qilish.', url: 'https://runwayml.com', icon: '🎬', status: 'active' },
];

export const MOCK_TERMINALS: TerminalStatus[] = [
  { id: 'Terminal 1', name: 'Touchscreen #1 (Kirish o‘ng)', status: 'online', ip: '192.168.1.101', uptime: '14 soat 22 daq', currentSessionId: 'sess_10928', lastActivity: 'Hozir' },
  { id: 'Terminal 2', name: 'Touchscreen #2 (Markaziy 1)', status: 'online', ip: '192.168.1.102', uptime: '14 soat 20 daq', currentSessionId: 'sess_10929', lastActivity: '2 daq oldin' },
  { id: 'Terminal 3', name: 'Touchscreen #3 (Markaziy 2)', status: 'idle', ip: '192.168.1.103', uptime: '10 soat 05 daq', lastActivity: '12 daq oldin' },
  { id: 'Terminal 4', name: 'Touchscreen #4 (Deraza oldi)', status: 'online', ip: '192.168.1.104', uptime: '8 soat 45 daq', currentSessionId: 'sess_10930', lastActivity: 'Hozir' },
];
